genshin_app_coordinate = [955, 1052]
pyautoguiFAILSAFE = True
notification = True
sort_mode = 1  # 0: time, 1: order, 2: name
midi_include_sharps = True
midi_beat_threshold = 0.0
midi_offset = 0
rows_count = 3
name_max_length = 30
search_break_weight_ratio = 2.0
search_max_missing = 2
backup = {}
